version: "3"
services:
  moniker:
    container_name: moniker
    image: ethanchrisp/moniker:latest
    environment:
      TWITTER_ACCESS_TOKEN: XXXXXXXX
      TWITTER_ACCESS_TOKEN_SECRET: XXXXXXXX
      TWITTER_API_KEY: XXXXXXXX
      TWITTER_API_KEY_SECRET: XXXXXXXX
      TWITTER_USERNAMES: username123,user_name,jack
      DISCORD_NOTIFY_WEBHOOK: https://discord.com/api/webhooks/XXXXXXXX/XXXXXXXX
      DISCORD_LOG_WEBHOOK: https://discord.com/api/webhooks/XXXXXXXX/XXXXXXXX
      DISCORD_LOG_LEVEL: WARNING
