[tool.poetry]
name = "moniker"
version = "1.0.0"
description = "Twitter username watcher that reports availability via Discord."
authors = ["EthanC <16727756+EthanC@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^0.21.1"
loguru = "^0.6.0"
notifiers = "^1.3.3"
tweepy = "^4.12.1"
discord-webhook = "^1.1.0"
httpx = "^0.23.3"

[tool.poetry.group.dev.dependencies]
pylint = "^2.16.2"
black = "^23.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
